// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/google/wire"
	"github.com/quockhanhcao/my-internet-download-manager/internal/configs"
	"github.com/quockhanhcao/my-internet-download-manager/internal/dataacess"
	"github.com/quockhanhcao/my-internet-download-manager/internal/dataacess/database"
	"github.com/quockhanhcao/my-internet-download-manager/internal/handler"
	"github.com/quockhanhcao/my-internet-download-manager/internal/handler/grpc"
	"github.com/quockhanhcao/my-internet-download-manager/internal/logic"
)

// Injectors from wire.go:

func InitializeGRPCServer(configFilePath configs.ConfigFilePath) (grpc.Server, func(), error) {
	config, err := configs.NewConfig(configFilePath)
	if err != nil {
		return nil, nil, err
	}
	databaseConfig := config.DatabaseConfig
	db, cleanup, err := database.InitializeDB(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	goquDatabase := database.InitializeGoquDB(db)
	accountDataAccessor := database.NewAccountDataAccessor(goquDatabase)
	accountPasswordDataAccessor := database.NewAccountPasswordDataAccessor(goquDatabase)
	accountConfig := config.AccountConfig
	hash := logic.NewHash(accountConfig)
	accountHandler := logic.NewAccountHandler(accountDataAccessor, accountPasswordDataAccessor, hash, goquDatabase)
	goLoadServiceServer := grpc.NewHandler(accountHandler)
	server := grpc.NewServer(goLoadServiceServer)
	return server, func() {
		cleanup()
	}, nil
}

// wire.go:

var WireSet = wire.NewSet(configs.WireSet, dataacess.WireSet, logic.WireSet, handler.WireSet)
